
server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.c6csxmxkinkd.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220929-min?allowMultiQueries=true
    username: admin
    password: 1q2w3e4r

  security:
    user:
      name: admin
      password: 1q2w3e4r
    oauth2:
      client:
        registration:
          google:
            clientId: 896391558584-72cd1h987k7dfojirvvu8srlg6tvbptj.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:/mingyeong/web/springboot/stussy-clone-20220929-min/upload/